services:
  db:
    image: postgres
    ports:
      - "5431:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres       # Change this to 'postgres' or any other name
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata:
